packages:
  - "apps/*"
  - "packages/*"
  - "tools/*"

# Catalog for shared dependencies
catalog:
  # Core dependencies
  react: ^18.2.0
  react-dom: ^18.2.0
  react-native: ^0.73.0

  # UI Components & Styling
  "@base-ui-components/react": ^1.0.0-beta.1
  clsx: ^2.1.0
  lucide-react: ^0.344.0
  tailwindcss: ^3.4.0
  "@tailwindcss/forms": ^0.5.7
  "@tailwindcss/typography": ^0.5.10
  autoprefixer: ^10.4.16
  postcss: ^8.4.32

  # State Management
  zustand: ^4.4.7
  "@tanstack/react-query": ^5.17.0

  # Form Handling
  "react-hook-form": ^7.48.2
  "@hookform/resolvers": ^3.3.2
  
  # TypeScript and tooling
  typescript: ^5.3.0
  "@types/node": ^20.11.0
  "@types/react": ^18.2.0
  "@types/react-dom": ^18.2.0
  "@types/react-native": ^0.73.0
  
  # Build tools
  vite: ^5.0.0
  "@vitejs/plugin-react": ^4.2.0
  
  # Networking & API
  axios: ^1.6.0
  ky: ^1.2.0

  # Database & ORM
  prisma: ^5.7.0
  "@prisma/client": ^5.7.0

  # Authentication
  "next-auth": ^4.24.5
  jsonwebtoken: ^9.0.2
  bcryptjs: ^2.4.3
  "@types/bcryptjs": ^2.4.6

  # Validation & Utilities
  zod: ^3.22.4
  date-fns: ^3.0.6
  lodash: ^4.17.21
  
  # Electron
  electron: ^28.0.0
  "@electron-forge/cli": ^7.2.0
  
  # React Native
  expo: ^50.0.0
  "@expo/config-plugins": ^7.8.0
  
  # Testing
  vitest: ^1.2.0
  "@testing-library/react": ^14.1.0
  "@testing-library/jest-dom": ^6.2.0
  "@testing-library/react-native": ^12.4.2
  "@testing-library/user-event": ^14.5.1
  msw: ^2.0.11

  # Development Tools
  "@storybook/react": ^7.6.6
  "@storybook/react-vite": ^7.6.6
  chromatic: ^10.2.0

  # Monitoring & Analytics
  "@sentry/react": ^7.91.0
  "@sentry/electron": ^4.15.0

  # Internationalization
  "react-i18next": ^13.5.0
  i18next: ^23.7.16
  
  # Linting and formatting
  eslint: ^8.56.0
  prettier: ^3.2.4
  "@typescript-eslint/eslint-plugin": ^6.19.0
  "@typescript-eslint/parser": ^6.19.0
