packages:
  - "apps/*"
  - "packages/*"
  - "tools/*"

# Catalog for shared dependencies
catalog:
  # Core dependencies
  react: ^18.2.0
  react-dom: ^18.2.0
  react-native: ^0.73.0

  # UI Components
  "@base-ui-components/react": ^1.0.0-beta.1
  clsx: ^2.1.0
  lucide-react: ^0.344.0
  
  # TypeScript and tooling
  typescript: ^5.3.0
  "@types/node": ^20.11.0
  "@types/react": ^18.2.0
  "@types/react-dom": ^18.2.0
  
  # Build tools
  vite: ^5.0.0
  "@vitejs/plugin-react": ^4.2.0
  
  # WebRTC and audio
  simple-peer: ^9.11.1
  socket.io: ^4.7.4
  socket.io-client: ^4.7.4
  
  # Electron
  electron: ^28.0.0
  "@electron-forge/cli": ^7.2.0
  
  # React Native
  expo: ^50.0.0
  "@expo/config-plugins": ^7.8.0
  
  # Testing
  vitest: ^1.2.0
  "@testing-library/react": ^14.1.0
  "@testing-library/jest-dom": ^6.2.0
  
  # Linting and formatting
  eslint: ^8.56.0
  prettier: ^3.2.4
  "@typescript-eslint/eslint-plugin": ^6.19.0
  "@typescript-eslint/parser": ^6.19.0
